version: '3.8'

services:
  stock_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    environment:
      SYMBOL: "${SYMBOL}"  
      NDAYS: "${NDAYS}" 
      API_KEY: "${API_KEY}"  
      REDIS_ADDR: "${REDIS_ADDR}"  

  redis:
    image: redis:latest  
    ports:
      - "6379:6379" 
