# apiVersion: v1
# kind: Secret
# metadata:
#   name: secrets
#   namespace: stock-ticker
# type: Opaque
# data:
#   API_KEY: API_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secrets
  namespace: stock-ticker
spec:
  data:
    - remoteRef:
        key: /dev/stock-ticker
        property: API_KEY
      secretKey: API_KEY